name: Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Build Docker image
        run: docker build -t atlascoders/myapp:${{ github.sha }} .

      - name: Push Docker image
        run: docker push atlascoder/myapp:${{ github.sha }}
